

# **Task 7: Logistic Regression – Titanic Survival Prediction**

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split

In [ ]:
df=pd.read_csv('Titanic-Dataset.csv')

In [ ]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

#Reviewing the important features

In [ ]:
# review important features like Age, Sex, Fare, and Survived.
df.Age.isnull().sum()

np.int64(177)

In [ ]:
df.Sex.isnull().sum()

np.int64(0)

In [ ]:
df.Fare.isnull().sum()

np.int64(0)

In [ ]:
df.Survived.unique().sum()

np.int64(1)

In [ ]:
df['Survived'].value_counts()# these values are un evenly distributed

Survived
0    549
1    342
Name: count, dtype: int64

In [ ]:
df_filtered=df.copy()

#Replacing the null values with median and mode

In [ ]:
df_filtered['Age'].describe().loc['50%']

np.float64(28.0)

In [ ]:
df_filtered['Age']=df_filtered['Age'].fillna(df_filtered['Age'].describe().loc['50%'])

In [ ]:
df_filtered['Embarked']=df_filtered['Embarked'].fillna(df_filtered['Embarked'].mode()[0])

In [ ]:
df_filtered.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         0
dtype: int64

#  Removing columns that are not nessasary

In [ ]:
df_filtered=df_filtered.drop(columns=['PassengerId','Name'],axis=0)

In [ ]:
df_filtered.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,0,3,male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,1,1,female,38.0,1,0,PC 17599,71.2833,C85,C
2,1,3,female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,1,1,female,35.0,1,0,113803,53.1000,C123,S
4,0,3,male,35.0,0,0,373450,8.0500,NaN,S

In [ ]:
from sklearn.preprocessing import OneHotEncoder

In [ ]:
ohe=OneHotEncoder(handle_unknown='ignore',sparse_output=False).set_output(transform="pandas")
encoded=ohe.fit_transform(df_filtered[['Sex','Embarked']])

In [ ]:
encoded

     Sex_female  Sex_male  Embarked_C  Embarked_Q  Embarked_S
0           0.0       1.0         0.0         0.0         1.0
1           1.0       0.0         1.0         0.0         0.0
2           1.0       0.0         0.0         0.0         1.0
3           1.0       0.0         0.0         0.0         1.0
4           0.0       1.0         0.0         0.0         1.0
..          ...       ...         ...         ...         ...
886         0.0       1.0         0.0         0.0         1.0
887         1.0       0.0         0.0         0.0         1.0
888         1.0       0.0         0.0         0.0         1.0
889         0.0       1.0         1.0         0.0         0.0
890         0.0       1.0         0.0         1.0         0.0

[891 rows x 5 columns]

In [ ]:
df_filtered=df_filtered.drop(columns=['Sex','Embarked'])

In [ ]:
df_filtered['Embarked_C']=encoded['Embarked_C']
df_filtered['Embarked_Q']=encoded['Embarked_Q']
df_filtered['Embarked_S']=encoded['Embarked_S']
df_filtered

,Survived,Pclass,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked_C,Embarked_Q,Embarked_S
0,0,3,22.0,1,0,A/5 21171,7.2500,NaN,0.0,0.0,1.0
1,1,1,38.0,1,0,PC 17599,71.2833,C85,1.0,0.0,0.0
2,1,3,26.0,0,0,STON/O2. 3101282,7.9250,NaN,0.0,0.0,1.0
3,1,1,35.0,1,0,113803,53.1000,C123,0.0,0.0,1.0
4,0,3,35.0,0,0,373450,8.0500,NaN,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,27.0,0,0,211536,13.0000,NaN,0.0,0.0,1.0
887,1,1,19.0,0,0,112053,30.0000,B42,0.0,0.0,1.0
888,0,3,28.0,1,2,W./C. 6607,23.4500,NaN,0.0,0.0,1.0
889,1,1,26.0,0,0,111369,30.0000,C148,1.0,0.0,0.0
890,0,3,32.0,0,0,370376,7.7500,NaN,0.0,1.0,0.0

In [ ]:
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

In [ ]:
sc=StandardScaler().set_output(transform="pandas")
after_scaling=sc.fit_transform(df_filtered[['Age','Fare']])

In [ ]:
after_scaling

          Age      Fare
0   -0.565736 -0.502445
1    0.663861  0.786845
2   -0.258337 -0.488854
3    0.433312  0.420730
4    0.433312 -0.486337
..        ...       ...
886 -0.181487 -0.386671
887 -0.796286 -0.044381
888 -0.104637 -0.176263
889 -0.258337 -0.044381
890  0.202762 -0.492378

[891 rows x 2 columns]

In [ ]:
df_filtered['age_scaled']=after_scaling['Age']
df_filtered['fare_scaled']=after_scaling['Fare']
df_filtered=df_filtered.drop(columns=['Age','Fare'])

In [ ]:
df_filtered

,Survived,Pclass,SibSp,Parch,Ticket,Cabin,Embarked_C,Embarked_Q,Embarked_S,age_scaled,fare_scaled
0,0,3,1,0,A/5 21171,NaN,0.0,0.0,1.0,-0.565736,-0.502445
1,1,1,1,0,PC 17599,C85,1.0,0.0,0.0,0.663861,0.786845
2,1,3,0,0,STON/O2. 3101282,NaN,0.0,0.0,1.0,-0.258337,-0.488854
3,1,1,1,0,113803,C123,0.0,0.0,1.0,0.433312,0.420730
4,0,3,0,0,373450,NaN,0.0,0.0,1.0,0.433312,-0.486337
...,...,...,...,...,...,...,...,...,...,...,...
886,0,2,0,0,211536,NaN,0.0,0.0,1.0,-0.181487,-0.386671
887,1,1,0,0,112053,B42,0.0,0.0,1.0,-0.796286,-0.044381
888,0,3,1,2,W./C. 6607,NaN,0.0,0.0,1.0,-0.104637,-0.176263
889,1,1,0,0,111369,C148,1.0,0.0,0.0,-0.258337,-0.044381
890,0,3,0,0,370376,NaN,0.0,1.0,0.0,0.202762,-0.492378

In [ ]:
x=df_filtered.drop(columns=['Survived'])
y=df_filtered['Survived']
x

,Pclass,SibSp,Parch,Ticket,Cabin,Embarked_C,Embarked_Q,Embarked_S,age_scaled,fare_scaled
0,3,1,0,A/5 21171,NaN,0.0,0.0,1.0,-0.565736,-0.502445
1,1,1,0,PC 17599,C85,1.0,0.0,0.0,0.663861,0.786845
2,3,0,0,STON/O2. 3101282,NaN,0.0,0.0,1.0,-0.258337,-0.488854
3,1,1,0,113803,C123,0.0,0.0,1.0,0.433312,0.420730
4,3,0,0,373450,NaN,0.0,0.0,1.0,0.433312,-0.486337
...,...,...,...,...,...,...,...,...,...,...
886,2,0,0,211536,NaN,0.0,0.0,1.0,-0.181487,-0.386671
887,1,0,0,112053,B42,0.0,0.0,1.0,-0.796286,-0.044381
888,3,1,2,W./C. 6607,NaN,0.0,0.0,1.0,-0.104637,-0.176263
889,1,0,0,111369,C148,1.0,0.0,0.0,-0.258337,-0.044381
890,3,0,0,370376,NaN,0.0,1.0,0.0,0.202762,-0.492378

In [ ]:
x=x.drop(columns=['Cabin','Ticket'])

In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=40)

In [ ]:
x_train.shape
x_test.shape

(268, 8)

In [ ]:
model=LogisticRegression()
model.fit(x_train,y_train)

LogisticRegression()

In [ ]:
y_predict=model.predict(x_test)

In [ ]:
from sklearn.metrics import accuracy_score,precision_score,f1_score,recall_score,confusion_matrix

In [ ]:
accuracy=accuracy_score(y_test,y_predict)
accuracy

0.7201492537313433

In [ ]:
precision=precision_score(y_test,y_predict)

recall=recall_score(y_test,y_predict)
f1=f1_score(y_test,y_predict)

In [ ]:
print(accuracy)
print(f1)
print(precision)
print(recall)

0.7201492537313433
0.5901639344262295
0.7605633802816901
0.48214285714285715

In [ ]:
confusion_matrix=confusion_matrix(y_test,y_predict)
confusion_matrix

array([[139,  17],
       [ 58,  54]])

In [ ]:
from sklearn.metrics import roc_curve, auc
y_prob = model.predict_proba(x_test)[:, 1]

# Calculate ROC values
fpr, tpr, thresholds = roc_curve(y_test, y_prob)

# Calculate AUC

roc_auc = auc(fpr, tpr)

In [ ]:
roc_auc

np.float64(0.7496565934065934)